version: '3'
# Three services are started
# (Two Apaches infront of a HAProxy load balancer)
services:
  # Tool for analyzing the SSL configuration of the HAProxy
  osaft:
    image: owasp/o-saft
    command: ["+check", "haproxy"]
    container_name: osaft
    networks:
      - backend
  apache-1:
    image: httpd
    container_name: apache-1
    # Both Apache containers host a different index.html
    volumes:
      - ./index1.html:/usr/local/apache2/htdocs/index.html:ro
    networks:
      - backend
  apache-2:
    image: httpd
    container_name: apache-2
    volumes:
      - ./index2.html:/usr/local/apache2/htdocs/index.html:ro
    networks:
      - backend
  haproxy:
    image: haproxy
    container_name: haproxy
    volumes:
      # Mount the proxy configuration
      - ./haproxy-tls1_2.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      # Change the host file path to a different config. For example test a TLS 1.3 configuration
      # - ./haproxy-tls1_3.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      # The generated certificate (generated by the create-certificate.sh)
      - ./certificate-chain.pem:/etc/ssl/certs/certificate-chain.pem:ro
      # Mount the generated DH Paramters (only required for TLS 1.2 configuration)
      - ./dhparams.pem:/etc/ssl/certs/dhparams.pem:ro
    # Only the HAProxy ports need to be forwarded
    ports:
      - 80:80
      - 443:443
    networks:
      - backend
# A network allows to certain containers to communicate with each other 
networks:
  backend:
